package com.stefanini.model;
// default package
// Generated 09/11/2016 08:59:45 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Infracoes generated by hbm2java
 */
@Entity
@Table(name = "infracoes", catalog = "hackathon")
public class Infracoes implements java.io.Serializable {

	private Integer idInfracao;
	private Agente agente;
	private LocalInfracao localinfracao;
	private TipoInfracao tipoinfracao;
	private Veiculos veiculos;
	private Integer velocidade;

	public Infracoes() {
	}

	public Infracoes(Agente agente, LocalInfracao localinfracao, TipoInfracao tipoinfracao, Veiculos veiculos) {
		this.agente = agente;
		this.localinfracao = localinfracao;
		this.tipoinfracao = tipoinfracao;
		this.veiculos = veiculos;
	}

	public Infracoes(Agente agente, LocalInfracao localinfracao, TipoInfracao tipoinfracao, Veiculos veiculos,
			Integer velocidade) {
		this.agente = agente;
		this.localinfracao = localinfracao;
		this.tipoinfracao = tipoinfracao;
		this.veiculos = veiculos;
		this.velocidade = velocidade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idInfracao", unique = true, nullable = false)
	public Integer getIdInfracao() {
		return this.idInfracao;
	}

	public void setIdInfracao(Integer idInfracao) {
		this.idInfracao = idInfracao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAgente", nullable = false)
	public Agente getAgente() {
		return this.agente;
	}

	public void setAgente(Agente agente) {
		this.agente = agente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocalInfracao", nullable = false)
	public LocalInfracao getLocalinfracao() {
		return this.localinfracao;
	}

	public void setLocalinfracao(LocalInfracao localinfracao) {
		this.localinfracao = localinfracao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoInfracao", nullable = false)
	public TipoInfracao getTipoinfracao() {
		return this.tipoinfracao;
	}

	public void setTipoinfracao(TipoInfracao tipoinfracao) {
		this.tipoinfracao = tipoinfracao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "placa", nullable = false)
	public Veiculos getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Veiculos veiculos) {
		this.veiculos = veiculos;
	}

	@Column(name = "velocidade")
	public Integer getVelocidade() {
		return this.velocidade;
	}

	public void setVelocidade(Integer velocidade) {
		this.velocidade = velocidade;
	}

}
