package com.stefanini.model;
// Generated 07/11/2016 12:04:57 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Infracoes generated by hbm2java
 */
@Entity
@Table(name = "infracoes", catalog = "hackathon")
public class Infracoes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idInfracao", unique = true, nullable = false)
	private Integer idInfracao;
	
	@Column(name = "idAgente", nullable = false)
	private Agente agente;
	
	@Column(name = "idLocalInfracao", nullable = false)
	private LocalInfracao localInfracao;
	
	@Column(name = "idTipoInfracao", nullable = false)
	private TipoInfracao tipoInfracao;
	
	@Column(name = "placa", nullable = false, length = 7)
	private Veiculos veiculo;
	
	@Column(name = "velocidade")
	private Integer velocidade;

	public Infracoes() {
	}

	public Infracoes(Agente agente, LocalInfracao localinfracao, TipoInfracao tipoinfracao, Veiculos veiculo) {
		this.agente = agente;
		this.localInfracao = localinfracao;
		this.tipoInfracao = tipoinfracao;
		this.veiculo = veiculo;
	}

	public Integer getIdInfracao() {
		return this.idInfracao;
	}

	public void setIdInfracao(Integer idInfracao) {
		this.idInfracao = idInfracao;
	}
	
	public Agente getAgente() {
		return this.agente;
	}

	public void setAgente(Agente agente) {
		this.agente = agente;
	}

	public LocalInfracao getLocalInfracao() {
		return this.localInfracao;
	}

	public void setLocalInfracao(LocalInfracao localInfracao) {
		this.localInfracao = localInfracao;
	}

	public TipoInfracao getTipoInfracao() {
		return this.tipoInfracao;
	}

	public void setTipoInfracao(TipoInfracao tipoInfracao) {
		this.tipoInfracao = tipoInfracao;
	}
	
	public Veiculos getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculos(Veiculos veiculo) {
		this.veiculo = veiculo;
	}

	public Integer getVelocidade() {
		return this.velocidade;
	}

	public void setVelocidade(Integer velocidade) {
		this.velocidade = velocidade;
	}

}
