package com.stefanini.model;
// default package
// Generated 09/11/2016 08:59:45 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonesId generated by hbm2java
 */
@Embeddable
public class TelefonesId implements java.io.Serializable {

	private int numero;
	private int ddd;

	public TelefonesId() {
	}

	public TelefonesId(int numero, int ddd) {
		this.numero = numero;
		this.ddd = ddd;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "ddd", nullable = false)
	public int getDdd() {
		return this.ddd;
	}

	public void setDdd(int ddd) {
		this.ddd = ddd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelefonesId))
			return false;
		TelefonesId castOther = (TelefonesId) other;

		return (this.getNumero() == castOther.getNumero()) && (this.getDdd() == castOther.getDdd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumero();
		result = 37 * result + this.getDdd();
		return result;
	}

}
