package com.stefanini.model;
// default package
// Generated 09/11/2016 08:59:45 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotelefone generated by hbm2java
 */
@Entity
@Table(name = "tipotelefone", catalog = "hackathon")
public class Tipotelefone implements java.io.Serializable {

	private Integer idTipoTelefone;
	private String descricaoTipoTelefone;
	private Set<Telefones> telefoneses = new HashSet<Telefones>(0);

	public Tipotelefone() {
	}

	public Tipotelefone(String descricaoTipoTelefone, Set<Telefones> telefoneses) {
		this.descricaoTipoTelefone = descricaoTipoTelefone;
		this.telefoneses = telefoneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoTelefone", unique = true, nullable = false)
	public Integer getIdTipoTelefone() {
		return this.idTipoTelefone;
	}

	public void setIdTipoTelefone(Integer idTipoTelefone) {
		this.idTipoTelefone = idTipoTelefone;
	}

	@Column(name = "descricaoTipoTelefone", length = 20)
	public String getDescricaoTipoTelefone() {
		return this.descricaoTipoTelefone;
	}

	public void setDescricaoTipoTelefone(String descricaoTipoTelefone) {
		this.descricaoTipoTelefone = descricaoTipoTelefone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipotelefone")
	public Set<Telefones> getTelefoneses() {
		return this.telefoneses;
	}

	public void setTelefoneses(Set<Telefones> telefoneses) {
		this.telefoneses = telefoneses;
	}

}
