package com.stefanini.model;
// default package
// Generated 09/11/2016 08:59:45 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoinfracao generated by hbm2java
 */
@Entity
@Table(name = "tipoinfracao", catalog = "hackathon")
public class TipoInfracao implements java.io.Serializable {

	private Integer idTipoInfracao;
	private String descricaoTipoInfracao;
	private Double valor;
	private Set<Infracoes> infracoeses = new HashSet<Infracoes>(0);

	public TipoInfracao() {
	}

	public TipoInfracao(String descricaoTipoInfracao, Double valor, Set<Infracoes> infracoeses) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
		this.valor = valor;
		this.infracoeses = infracoeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoInfracao", unique = true, nullable = false)
	public Integer getIdTipoInfracao() {
		return this.idTipoInfracao;
	}

	public void setIdTipoInfracao(Integer idTipoInfracao) {
		this.idTipoInfracao = idTipoInfracao;
	}

	@Column(name = "descricaoTipoInfracao", length = 50)
	public String getDescricaoTipoInfracao() {
		return this.descricaoTipoInfracao;
	}

	public void setDescricaoTipoInfracao(String descricaoTipoInfracao) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
	}

	@Column(name = "valor", precision = 22, scale = 0)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoinfracao")
	public Set<Infracoes> getInfracoeses() {
		return this.infracoeses;
	}

	public void setInfracoeses(Set<Infracoes> infracoeses) {
		this.infracoeses = infracoeses;
	}

}
